// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: alerts.sql

package db

import (
	"context"
	"time"
)

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (
    rule_id,
    market_id,
    outcome,
    outcome_id,
    observed_price,
    trigger_value,
    trigger_sequence,
    triggered_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAlertParams struct {
	RuleID          string    `json:"rule_id"`
	MarketID        string    `json:"market_id"`
	Outcome         string    `json:"outcome"`
	OutcomeID       string    `json:"outcome_id"`
	ObservedPrice   float64   `json:"observed_price"`
	TriggerValue    float64   `json:"trigger_value"`
	TriggerSequence int64     `json:"trigger_sequence"`
	TriggeredAt     time.Time `json:"triggered_at"`
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert,
		arg.RuleID,
		arg.MarketID,
		arg.Outcome,
		arg.OutcomeID,
		arg.ObservedPrice,
		arg.TriggerValue,
		arg.TriggerSequence,
		arg.TriggeredAt,
	)
	return err
}
