// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Alert struct {
	ID              string    `json:"id"`
	RuleID          string    `json:"rule_id"`
	MarketID        string    `json:"market_id"`
	Outcome         string    `json:"outcome"`
	OutcomeID       string    `json:"outcome_id"`
	ObservedPrice   float64   `json:"observed_price"`
	TriggerValue    float64   `json:"trigger_value"`
	TriggerSequence int64     `json:"trigger_sequence"`
	TriggeredAt     time.Time `json:"triggered_at"`
	CreatedAt       time.Time `json:"created_at"`
}

type PriceSample struct {
	ID         int64     `json:"id"`
	MarketID   string    `json:"market_id"`
	OutcomeID  string    `json:"outcome_id"`
	Price      float64   `json:"price"`
	ObservedAt time.Time `json:"observed_at"`
}

type Rule struct {
	ID              string    `json:"id"`
	EventID         string    `json:"event_id"`
	EventSlug       string    `json:"event_slug"`
	MarketID        string    `json:"market_id"`
	Outcome         string    `json:"outcome"`
	OutcomeID       string    `json:"outcome_id"`
	Type            string    `json:"type"`
	Direction       string    `json:"direction"`
	Target          float64   `json:"target"`
	Percent         float64   `json:"percent"`
	WindowSeconds   int32     `json:"window_seconds"`
	Enabled         bool      `json:"enabled"`
	State           []byte    `json:"state"`
	TriggerSequence int64     `json:"trigger_sequence"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
