// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: price_smaples.sql

package db

import (
	"context"
	"time"
)

const insertPriceSample = `-- name: InsertPriceSample :exec
INSERT INTO price_samples (market_id, outcome_id, price, observed_at)
VALUES ($1, $2, $3, $4)
`

type InsertPriceSampleParams struct {
	MarketID   string    `json:"market_id"`
	OutcomeID  string    `json:"outcome_id"`
	Price      float64   `json:"price"`
	ObservedAt time.Time `json:"observed_at"`
}

func (q *Queries) InsertPriceSample(ctx context.Context, arg InsertPriceSampleParams) error {
	_, err := q.db.Exec(ctx, insertPriceSample,
		arg.MarketID,
		arg.OutcomeID,
		arg.Price,
		arg.ObservedAt,
	)
	return err
}

const listPriceSamplesForWindow = `-- name: ListPriceSamplesForWindow :many
SELECT price, observed_at
FROM price_samples
WHERE market_id = $1
  AND outcome_id = $2
  AND observed_at >= $3
  AND observed_at <= $4
ORDER BY observed_at ASC
`

type ListPriceSamplesForWindowParams struct {
	MarketID     string    `json:"market_id"`
	OutcomeID    string    `json:"outcome_id"`
	ObservedAt   time.Time `json:"observed_at"`
	ObservedAt_2 time.Time `json:"observed_at_2"`
}

type ListPriceSamplesForWindowRow struct {
	Price      float64   `json:"price"`
	ObservedAt time.Time `json:"observed_at"`
}

func (q *Queries) ListPriceSamplesForWindow(ctx context.Context, arg ListPriceSamplesForWindowParams) ([]ListPriceSamplesForWindowRow, error) {
	rows, err := q.db.Query(ctx, listPriceSamplesForWindow,
		arg.MarketID,
		arg.OutcomeID,
		arg.ObservedAt,
		arg.ObservedAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceSamplesForWindowRow
	for rows.Next() {
		var i ListPriceSamplesForWindowRow
		if err := rows.Scan(&i.Price, &i.ObservedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
