// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: rules.sql

package db

import (
	"context"
)

const createRule = `-- name: CreateRule :one
INSERT INTO rules (
    event_id,
    event_slug,
    market_id,
    outcome,
    outcome_id,
    type,
    direction,
    target,
    percent,
    window_seconds,
    state
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, event_id, event_slug, market_id, outcome, outcome_id, type,
    direction, target, percent, window_seconds, enabled, state, trigger_sequence,
    created_at, updated_at
`

type CreateRuleParams struct {
	EventID       string  `json:"event_id"`
	EventSlug     string  `json:"event_slug"`
	MarketID      string  `json:"market_id"`
	Outcome       string  `json:"outcome"`
	OutcomeID     string  `json:"outcome_id"`
	Type          string  `json:"type"`
	Direction     string  `json:"direction"`
	Target        float64 `json:"target"`
	Percent       float64 `json:"percent"`
	WindowSeconds int32   `json:"window_seconds"`
	State         []byte  `json:"state"`
}

func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.EventID,
		arg.EventSlug,
		arg.MarketID,
		arg.Outcome,
		arg.OutcomeID,
		arg.Type,
		arg.Direction,
		arg.Target,
		arg.Percent,
		arg.WindowSeconds,
		arg.State,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventSlug,
		&i.MarketID,
		&i.Outcome,
		&i.OutcomeID,
		&i.Type,
		&i.Direction,
		&i.Target,
		&i.Percent,
		&i.WindowSeconds,
		&i.Enabled,
		&i.State,
		&i.TriggerSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuleForUpdate = `-- name: GetRuleForUpdate :one
SELECT id, event_id, event_slug, market_id, outcome, outcome_id, type,
    direction, target, percent, window_seconds, enabled, state, trigger_sequence,
    created_at, updated_at
FROM rules
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetRuleForUpdate(ctx context.Context, id string) (Rule, error) {
	row := q.db.QueryRow(ctx, getRuleForUpdate, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventSlug,
		&i.MarketID,
		&i.Outcome,
		&i.OutcomeID,
		&i.Type,
		&i.Direction,
		&i.Target,
		&i.Percent,
		&i.WindowSeconds,
		&i.Enabled,
		&i.State,
		&i.TriggerSequence,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRules = `-- name: ListEnabledRules :many
SELECT id, event_id, event_slug, market_id, outcome, outcome_id, type,
    direction, target, percent, window_seconds, enabled, state, trigger_sequence,
    created_at, updated_at
FROM rules
WHERE enabled = true
ORDER BY created_at ASC
`

func (q *Queries) ListEnabledRules(ctx context.Context) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listEnabledRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rule
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventSlug,
			&i.MarketID,
			&i.Outcome,
			&i.OutcomeID,
			&i.Type,
			&i.Direction,
			&i.Target,
			&i.Percent,
			&i.WindowSeconds,
			&i.Enabled,
			&i.State,
			&i.TriggerSequence,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRuleState = `-- name: UpdateRuleState :exec
UPDATE rules
SET state = $1,
    trigger_sequence = $2,
    updated_at = now()
WHERE id = $3
`

type UpdateRuleStateParams struct {
	State           []byte `json:"state"`
	TriggerSequence int64  `json:"trigger_sequence"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateRuleState(ctx context.Context, arg UpdateRuleStateParams) error {
	_, err := q.db.Exec(ctx, updateRuleState, arg.State, arg.TriggerSequence, arg.ID)
	return err
}
